import { Project, Type, Symbol as MorphSymbol } from "ts-morph";
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const HEADER = `// AUTO-GENERATED by scripts/generate-schemas.ts — DO NOT EDIT
// Re-generate: yarn workspace @casehubio/pages-schema run generate
// Source: packages/pages-component/src/model/
import { z } from "zod";
import { lookupSchema } from "@casehubio/pages-data";
`;

const FUNCTION_PROPS = new Set([
  "cellSpan", "mergeRows", "renderAfterHeader",
  "columnRenderers", "rowKey",
]);

function isFunction(type: Type): boolean {
  return type.getCallSignatures().length > 0;
}

function typeToZod(type: Type, depth: number): string {
  if (depth > 6) return "z.unknown()";

  const text = type.getText();

  if (text.includes("DataSetLookup")) return "lookupSchema";
  if (text === "ColumnId" || text.includes("ColumnId")) return "z.string()";
  if (text === "DataSetId" || text.includes("DataSetId")) return "z.string()";
  if (text.includes("FieldSchema")) return "fieldSchemaZod";

  if (type.isString() || type.isStringLiteral()) return "z.string()";
  if (type.isNumber() || type.isNumberLiteral()) return "z.number()";
  if (type.isBoolean() || type.isBooleanLiteral()) return "z.boolean()";
  if (type.isNull()) return "z.null()";
  if (type.isUndefined()) return "z.undefined()";

  if (type.isUnion()) {
    const members = type.getUnionTypes().filter(t => !t.isUndefined());
    if (members.length === 0) return "z.undefined()";
    if (members.every(m => m.isStringLiteral())) {
      const values = members.map(m => JSON.stringify(m.getLiteralValue()));
      return `z.enum([${values.join(", ")}])`;
    }
    if (members.every(m => m.isBooleanLiteral())) return "z.boolean()";
    if (members.length === 1) return typeToZod(members[0], depth + 1);
    const zodMembers = members.map(m => typeToZod(m, depth + 1));
    if (zodMembers.length === 2) return `z.union([${zodMembers.join(", ")}])`;
    return `z.union([${zodMembers.join(", ")}])`;
  }

  if (type.isArray()) {
    const elem = type.getArrayElementType();
    if (!elem) return "z.array(z.unknown())";
    return `z.array(${typeToZod(elem, depth + 1)})`;
  }

  if (text.startsWith("readonly ") && text.endsWith("[]")) {
    const inner = type.getTypeArguments()[0];
    if (inner) return `z.array(${typeToZod(inner, depth + 1)})`;
    return "z.array(z.unknown())";
  }

  if (text.startsWith("Record<") || text.startsWith("Readonly<Record<")
      || text.includes("Record<string,")) {
    const typeArgs = type.getAliasTypeArguments();
    if (typeArgs.length === 2) {
      return `z.record(${typeToZod(typeArgs[1], depth + 1)})`;
    }
    const apparentProps = type.getStringIndexType();
    if (apparentProps) return `z.record(${typeToZod(apparentProps, depth + 1)})`;
    return "z.record(z.unknown())";
  }

  if (type.isObject() && !type.isArray()) {
    const props = type.getProperties();
    if (props.length === 0) return "z.object({})";
    const fields = props
      .map(p => propToZodField(p, depth + 1))
      .filter(Boolean);
    if (fields.length === 0) return "z.object({})";
    const indent = "  ".repeat(depth + 2);
    const closingIndent = "  ".repeat(depth + 1);
    return `z.object({\n${indent}${fields.join(`,\n${indent}`)},\n${closingIndent}})`;
  }

  return "z.unknown()";
}

function propToZodField(prop: MorphSymbol, depth: number): string {
  const name = prop.getName();
  if (FUNCTION_PROPS.has(name)) return "";
  if (name.startsWith("x-")) return "";

  const decl = prop.getValueDeclaration();
  if (!decl) return "";

  const type = prop.getTypeAtLocation(decl);
  if (isFunction(type)) return "";

  const isOptional = prop.isOptional();
  const baseType = isOptional ? type.getNonNullableType() : type;
  let zodType = typeToZod(baseType, depth);
  if (!zodType) return "";
  if (isOptional) zodType += ".optional()";

  const safeName = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : `"${name}"`;
  return `${safeName}: ${zodType}`;
}

function kebabToCamel(s: string): string {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

const project = new Project({
  tsConfigFilePath: resolve(__dirname, "../../pages-component/tsconfig.json"),
  skipAddingFilesFromTsConfig: false,
});

const typeGuardsFile = project.getSourceFileOrThrow(
  resolve(__dirname, "../../pages-component/src/model/type-guards.ts"),
);

const registry = typeGuardsFile.getInterfaceOrThrow("ComponentTypeRegistry");
const registryType = registry.getType();

const fieldSchemaBlock = `const fieldSchemaZod: z.ZodType<unknown> = z.lazy(() =>
  z.object({
    type: z.union([z.string(), z.array(z.string())]).optional(),
    format: z.string().optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    enum: z.array(z.string()).optional(),
    pattern: z.string().optional(),
    minimum: z.number().optional(),
    maximum: z.number().optional(),
    exclusiveMinimum: z.number().optional(),
    exclusiveMaximum: z.number().optional(),
    minLength: z.number().optional(),
    maxLength: z.number().optional(),
    minItems: z.number().optional(),
    maxItems: z.number().optional(),
    uniqueItems: z.boolean().optional(),
    multipleOf: z.number().optional(),
    readOnly: z.boolean().optional(),
    properties: z.record(fieldSchemaZod).optional(),
    required: z.array(z.string()).optional(),
    items: fieldSchemaZod.optional(),
    const: z.union([z.string(), z.number(), z.boolean(), z.null()]).optional(),
    oneOf: z.array(fieldSchemaZod).optional(),
    $ref: z.string().optional(),
    $defs: z.record(fieldSchemaZod).optional(),
    definitions: z.record(fieldSchemaZod).optional(),
  }).passthrough(),
);
`;

const output: string[] = [HEADER, fieldSchemaBlock];
const schemaNames: { key: string; camelName: string }[] = [];

for (const prop of registryType.getProperties()) {
  const registryKey = prop.getName();

  const decl = prop.getValueDeclaration();
  if (!decl) continue;
  const propType = prop.getTypeAtLocation(decl);

  const typeSymbol = propType.getSymbol() || propType.getAliasSymbol();
  const tsTypeName = typeSymbol?.getName();
  let camelName: string;
  if (tsTypeName && tsTypeName.endsWith("Props")) {
    const base = tsTypeName.slice(0, -5);
    camelName = base.charAt(0).toLowerCase() + base.slice(1) + "PropsSchema";
  } else {
    camelName = kebabToCamel(registryKey) + "PropsSchema";
  }

  const allProps = propType.getProperties();
  const fields = allProps
    .map(p => propToZodField(p, 0))
    .filter(Boolean);

  if (fields.length === 0) {
    output.push(`export const ${camelName} = z.object({});`);
  } else {
    output.push(`export const ${camelName} = z.object({\n  ${fields.join(",\n  ")},\n});`);
  }
  output.push("");
  schemaNames.push({ key: registryKey, camelName });
}

const mapEntries = schemaNames
  .map(({ key, camelName }) => `  ["${key}", ${camelName}]`)
  .join(",\n");
output.push(`export const componentSchemaMap: ReadonlyMap<string, z.ZodType> = new Map([
${mapEntries},
]);
`);

const outPath = resolve(__dirname, "../src/component-schemas.generated.ts");
writeFileSync(outPath, output.join("\n"), "utf-8");
console.log(`Generated ${schemaNames.length} schemas to ${outPath}`);
