quarkus.http.port=8090
quarkus.http.cors=true

%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pages_demo
%prod.quarkus.datasource.username=pages
%prod.quarkus.datasource.password=pages

casehub.pages.push.max-events-per-topic=500
