quarkus.http.port=8090
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pages_demo
quarkus.datasource.username=pages
quarkus.datasource.password=pages

casehub.pages.push.max-events-per-topic=500
