package io.casehub.pages.scenario;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class ScenarioParserTest {

    @Test
    void parsesHelpdeskIntakeScenario() throws IOException {
        Scenario scenario = ScenarioParser.parse(fixture("helpdesk-intake.yaml"));

        assertThat(scenario.scenario()).isEqualTo("helpdesk-intake");
        assertThat(scenario.steps()).hasSize(7);
        assertThat(scenario.steps()).allSatisfy(
                step -> assertThat(step).isInstanceOf(ScenarioStep.AriaStep.class));
    }

    @Test
    void parsesNavigateStep() throws IOException {
        Scenario scenario = ScenarioParser.parse(fixture("helpdesk-intake.yaml"));
        var step = (ScenarioStep.AriaStep) scenario.steps().get(0);

        assertThat(step.action()).isEqualTo("navigate");
        assertThat(step.value()).isEqualTo("/helpdesk/intake");
        assertThat(step.target()).isNull();
        assertThat(step.name()).isEqualTo("navigate-/helpdesk/intake");
    }

    @Test
    void parsesFillStep() throws IOException {
        Scenario scenario = ScenarioParser.parse(fixture("helpdesk-intake.yaml"));
        var step = (ScenarioStep.AriaStep) scenario.steps().get(1);

        assertThat(step.action()).isEqualTo("fill");
        assertThat(step.target()).isNotNull();
        assertThat(step.target().role()).isEqualTo("textbox");
        assertThat(step.target().name()).isEqualTo("Customer Name");
        assertThat(step.value()).isEqualTo("Alice Chen");
    }

    @Test
    void parsesSelectStep() throws IOException {
        Scenario scenario = ScenarioParser.parse(fixture("helpdesk-intake.yaml"));
        var step = (ScenarioStep.AriaStep) scenario.steps().get(3);

        assertThat(step.action()).isEqualTo("select");
        assertThat(step.target().role()).isEqualTo("combobox");
        assertThat(step.target().name()).isEqualTo("Priority");
        assertThat(step.value()).isEqualTo("High");
    }

    @Test
    void parsesClickStep() throws IOException {
        Scenario scenario = ScenarioParser.parse(fixture("helpdesk-intake.yaml"));
        var step = (ScenarioStep.AriaStep) scenario.steps().get(4);

        assertThat(step.action()).isEqualTo("click");
        assertThat(step.target().role()).isEqualTo("button");
        assertThat(step.target().name()).isEqualTo("Submit");
        assertThat(step.value()).isNull();
    }

    @Test
    void parsesAssertStep() throws IOException {
        Scenario scenario = ScenarioParser.parse(fixture("helpdesk-intake.yaml"));
        var step = (ScenarioStep.AriaStep) scenario.steps().get(5);

        assertThat(step.action()).isEqualTo("assert");
        assertThat(step.target().role()).isEqualTo("alert");
        assertThat(step.target().name()).isEqualTo("Submission confirmation");
        assertThat(step.state()).containsEntry("aria-hidden", false);
    }

    @Test
    void parsesWaitStep() throws IOException {
        Scenario scenario = ScenarioParser.parse(fixture("helpdesk-intake.yaml"));
        var step = (ScenarioStep.AriaStep) scenario.steps().get(6);

        assertThat(step.action()).isEqualTo("wait");
        assertThat(step.target().role()).isEqualTo("button");
        assertThat(step.target().name()).isEqualTo("Submit");
        assertThat(step.state()).containsEntry("aria-busy", false);
        assertThat(step.timeout()).isEqualTo(5000);
    }

    @Test
    void parsesWithinScoping() throws IOException {
        Scenario scenario = ScenarioParser.parse(fixture("scoped-delete.yaml"));
        var step = (ScenarioStep.AriaStep) scenario.steps().get(0);

        assertThat(step.action()).isEqualTo("click");
        assertThat(step.target().role()).isEqualTo("button");
        assertThat(step.target().name()).isEqualTo("Delete");
        assertThat(step.target().within()).isNotNull();
        assertThat(step.target().within().role()).isEqualTo("row");
        assertThat(step.target().within().name()).isEqualTo("Case #42");
        assertThat(step.target().within().within()).isNull();
    }

    @Test
    void ariaShorthandProducesAutoGeneratedName() {
        String yaml = """
                scenario: shorthand
                steps:
                  - click:
                      role: button
                      name: Submit
                """;
        Scenario scenario = ScenarioParser.parse(yaml);
        var step = (ScenarioStep.AriaStep) scenario.steps().getFirst();
        assertThat(step.action()).isEqualTo("click");
        assertThat(step.name()).isEqualTo("click-button-Submit");
    }

    @Test
    void parsesGraphQLStep() throws IOException {
        Scenario scenario = ScenarioParser.parse(fixture("graphql-inject-chat.yaml"));

        assertThat(scenario.scenario()).isEqualTo("graphql-inject-chat");
        assertThat(scenario.steps()).hasSize(1);
        assertThat(scenario.steps().getFirst()).isInstanceOf(ScenarioStep.GraphQLStep.class);

        var step = (ScenarioStep.GraphQLStep) scenario.steps().getFirst();
        assertThat(step.name()).isEqualTo("inject-chat");
        assertThat(step.domain()).isEqualTo("connectors");
        assertThat(step.operation()).isEqualTo("injectChat");
        assertThat(step.params()).containsEntry("platform", "slack");
        assertThat(step.params()).containsEntry("sender", "Alice");
        assertThat(step.await()).isNull();
    }

    @Test
    void parsesHybridScenario() throws IOException {
        Scenario scenario = ScenarioParser.parse(fixture("hybrid-helpdesk.yaml"));

        assertThat(scenario.scenario()).isEqualTo("hybrid-helpdesk");
        assertThat(scenario.steps()).hasSize(5);
        assertThat(scenario.steps().get(0)).isInstanceOf(ScenarioStep.AriaStep.class);
        assertThat(scenario.steps().get(1)).isInstanceOf(ScenarioStep.AriaStep.class);
        assertThat(scenario.steps().get(2)).isInstanceOf(ScenarioStep.AriaStep.class);
        assertThat(scenario.steps().get(3)).isInstanceOf(ScenarioStep.GraphQLStep.class);
        assertThat(scenario.steps().get(4)).isInstanceOf(ScenarioStep.GraphQLStep.class);

        var await = ((ScenarioStep.GraphQLStep) scenario.steps().get(4)).await();
        assertThat(await).isNotNull();
        assertThat(await.match()).containsEntry("category", "HARDWARE");
        assertThat(await.timeout()).isEqualTo(30000);
        assertThat(await.interval()).isEqualTo(500);
    }

    @Test
    void parsesGraphQLStepWithAwait() {
        String yaml = """
                scenario: await-test
                steps:
                  - name: check
                    delivery: graphql
                    domain: engine
                    operation: caseContext
                    params:
                      caseId: "123"
                    await:
                      match:
                        status: "RESOLVED"
                      timeout: 10000
                      interval: 200
                """;
        Scenario scenario = ScenarioParser.parse(yaml);
        var step = (ScenarioStep.GraphQLStep) scenario.steps().getFirst();
        assertThat(step.await().match()).containsEntry("status", "RESOLVED");
        assertThat(step.await().timeout()).isEqualTo(10000);
        assertThat(step.await().interval()).isEqualTo(200);
    }

    @Test
    void rejectsMissingScenarioName() {
        assertThatThrownBy(() -> ScenarioParser.parse("steps:\n  - navigate: /foo"))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("scenario");
    }

    @Test
    void rejectsMissingSteps() {
        assertThatThrownBy(() -> ScenarioParser.parse("scenario: test"))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("steps");
    }

    @Test
    void rejectsUnknownAction() {
        String yaml = "scenario: test\nsteps:\n  - hover:\n      role: button\n      name: X";
        assertThatThrownBy(() -> ScenarioParser.parse(yaml))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("Unknown");
    }

    @Test
    void stepsListIsImmutable() throws IOException {
        Scenario scenario = ScenarioParser.parse(fixture("helpdesk-intake.yaml"));
        assertThatThrownBy(() -> scenario.steps().add(
            new ScenarioStep.AriaStep(null, "click", null, null, null, null)))
            .isInstanceOf(UnsupportedOperationException.class);
    }

    private static String fixture(String name) throws IOException {
        try (InputStream is = ScenarioParserTest.class.getResourceAsStream("/scenarios/" + name)) {
            if (is == null) throw new IOException("Fixture not found: " + name);
            return new String(is.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
