// AUTO-GENERATED by scripts/generate-schemas.ts — DO NOT EDIT
// Re-generate: yarn workspace @casehubio/pages-schema run generate
// Source: packages/pages-component/src/model/
import { z } from "zod";
import { lookupSchema } from "@casehubio/pages-data";

const fieldSchemaZod: z.ZodType<unknown> = z.lazy(() =>
  z.object({
    type: z.union([z.string(), z.array(z.string())]).optional(),
    format: z.string().optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    enum: z.array(z.string()).optional(),
    pattern: z.string().optional(),
    minimum: z.number().optional(),
    maximum: z.number().optional(),
    exclusiveMinimum: z.number().optional(),
    exclusiveMaximum: z.number().optional(),
    minLength: z.number().optional(),
    maxLength: z.number().optional(),
    minItems: z.number().optional(),
    maxItems: z.number().optional(),
    uniqueItems: z.boolean().optional(),
    multipleOf: z.number().optional(),
    readOnly: z.boolean().optional(),
    properties: z.record(fieldSchemaZod).optional(),
    required: z.array(z.string()).optional(),
    items: fieldSchemaZod.optional(),
    const: z.union([z.string(), z.number(), z.boolean(), z.null()]).optional(),
    oneOf: z.array(fieldSchemaZod).optional(),
    $ref: z.string().optional(),
    $defs: z.record(fieldSchemaZod).optional(),
    definitions: z.record(fieldSchemaZod).optional(),
  }).passthrough(),
);

export const gridPropsSchema = z.object({
  columns: z.number(),
});

export const columnsPropsSchema = z.object({
  distribution: z.array(z.number()),
});

export const rowsPropsSchema = z.object({});

export const stackPropsSchema = z.object({});

export const tabsPropsSchema = z.object({});

export const pillsPropsSchema = z.object({});

export const sidebarPropsSchema = z.object({});

export const treePropsSchema = z.object({});

export const menuPropsSchema = z.object({});

export const accordionPropsSchema = z.object({});

export const carouselPropsSchema = z.object({});

export const splitPropsSchema = z.object({
  direction: z.enum(["horizontal", "vertical"]),
  ratio: z.array(z.number()).optional(),
  minSizes: z.array(z.number()).optional(),
});

export const dockBarPropsSchema = z.object({
  orientation: z.enum(["horizontal", "vertical"]),
  items: z.array(z.object({
      icon: z.string(),
      label: z.string(),
      panelId: z.string(),
      defaultOpen: z.boolean().optional(),
      zone: z.string().optional(),
      allowedZones: z.array(z.enum(["left-top", "left-bottom", "right-top", "right-bottom", "bottom-left", "bottom-right"])).optional(),
      fixed: z.boolean().optional(),
    })),
  exclusive: z.boolean().optional(),
  side: z.enum(["left", "right", "bottom"]).optional(),
});

export const hostPanelPropsSchema = z.object({
  typeName: z.string(),
  panelProps: z.record(z.unknown()).optional(),
  lookup: lookupSchema.optional(),
  selectionSource: z.string().optional(),
});

export const floatingWorkspacePropsSchema = z.object({
  centre: z.union([z.record(z.unknown()), z.array(z.record(z.unknown()))]),
  frames: z.array(z.object({
      key: z.string(),
      tabs: z.array(z.object({
          key: z.string(),
          label: z.string(),
          icon: z.string().optional(),
          content: z.union([z.null(), z.record(z.unknown())]),
          children: z.object({
            layout: z.enum(["free", "tabbed", "accordion", "splith", "splitv", "content"]),
            tabs: z.array(z.object({
                key: z.unknown(),
                label: z.unknown(),
                icon: z.unknown().optional(),
                content: z.unknown(),
                children: z.unknown().optional(),
              })),
            layoutState: z.object({}).optional(),
          }).optional(),
        })),
      position: z.object({
        x: z.number(),
        y: z.number(),
      }).optional(),
      size: z.object({
        width: z.number(),
        height: z.number(),
      }).optional(),
      pinned: z.boolean().optional(),
      viewMode: z.enum(["accordion", "tab"]).optional(),
      allowViewToggle: z.boolean().optional(),
      allowAddTab: z.boolean().optional(),
      allowArrangement: z.boolean().optional(),
    })).optional(),
  organisers: z.boolean().optional(),
});

export const panelPropsSchema = z.object({
  title: z.string(),
});

export const htmlPropsSchema = z.object({
  content: z.string(),
});

export const markdownPropsSchema = z.object({
  content: z.string(),
});

export const titlePropsSchema = z.object({
  text: z.string(),
  size: z.string().optional(),
});

export const lazyPagePropsSchema = z.object({
  name: z.string(),
  href: z.string(),
});

export const pagePropsSchema = z.object({
  name: z.string().optional(),
  datasets: z.union([z.array(z.object({
        uuid: z.string(),
        name: z.string().optional(),
        join: z.string().optional(),
        serverQuery: z.boolean().optional(),
        serverPagination: z.object({
          offsetParam: z.string(),
          limitParam: z.string(),
          sortParam: z.string().optional(),
          orderParam: z.string().optional(),
          filterParam: z.string().optional(),
          defaultPageSize: z.number(),
          maxCachedPages: z.number().optional(),
          totalPath: z.string().optional(),
        }).optional(),
        method: z.enum(["GET", "POST", "PUT", "DELETE"]).optional(),
        headers: z.record(z.string()).optional(),
        query: z.record(z.string()).optional(),
        form: z.record(z.string()).optional(),
        body: z.string().optional(),
        cacheEnabled: z.boolean().optional(),
        cacheMaxRows: z.number().optional(),
        refreshTime: z.string().optional(),
        cacheTtl: z.string().optional(),
        keyColumn: z.string().optional(),
        url: z.string().optional(),
        content: z.string().optional(),
        dataPath: z.string().optional(),
        type: z.string().optional(),
        expression: z.string().optional(),
        columns: z.array(z.object({
            id: z.string(),
            name: z.string().optional(),
            type: z.enum(["DATE", "NUMBER", "LABEL", "TEXT"]),
          })).optional(),
        accumulate: z.boolean().optional(),
      })), z.array(z.object({
        id: z.string(),
        source: z.object({}),
        keyColumn: z.string().optional(),
        refreshTime: z.string().optional(),
        cacheTtl: z.string().optional(),
        serverPagination: z.object({
          offsetParam: z.string(),
          limitParam: z.string(),
          sortParam: z.string().optional(),
          orderParam: z.string().optional(),
          filterParam: z.string().optional(),
          defaultPageSize: z.number(),
          maxCachedPages: z.number().optional(),
          totalPath: z.string().optional(),
        }).optional(),
      }))]).optional(),
  settings: z.object({
    mode: z.enum(["light", "dark"]).optional(),
    allowUrlProperties: z.boolean().optional(),
    dataComponentDefaults: z.object({
      lookup: z.object({
        dataSetId: z.string().optional(),
        operations: z.array(z.union([z.object({
              type: z.string(),
              expressions: z.array(z.unknown()),
            }), z.object({
              type: z.string(),
              groupingKey: z.union([z.unknown(), z.unknown()]),
              columns: z.array(z.unknown()),
              selectedIntervals: z.array(z.unknown()).optional(),
              join: z.boolean().optional(),
            }), z.object({
              type: z.string(),
              columns: z.array(z.unknown()),
            })])).optional(),
        rowCount: z.number().optional(),
        rowOffset: z.number().optional(),
      }).optional(),
      chart: z.object({}).optional(),
    }).optional(),
    datasetDefaults: z.object({
      url: z.string().optional(),
      content: z.string().optional(),
      method: z.enum(["GET", "POST", "PUT", "DELETE"]).optional(),
      headers: z.record(z.string()).optional(),
      columns: z.array(z.object({
          id: z.string(),
          name: z.string().optional(),
          type: z.enum(["DATE", "NUMBER", "LABEL", "TEXT"]),
        })).optional(),
      cacheEnabled: z.boolean().optional(),
      refreshTime: z.string().optional(),
    }).optional(),
  }).optional(),
  properties: z.record(z.string()).optional(),
  dataScope: z.object({
    dataset: z.string(),
    idColumn: z.string(),
    filter: z.record(z.union([z.string(), z.object({
          $ref: z.string(),
        })])).optional(),
  }).optional(),
  save: z.object({
    trigger: z.enum(["auto", "field", "button", "manual"]).optional(),
    delay: z.number().optional(),
    adapter: z.string(),
    adapterConfig: z.record(z.unknown()).optional(),
  }).optional(),
});

export const barChartPropsSchema = z.object({
  subtype: z.enum(["column", "column-stacked", "bar", "bar-stacked"]).optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const lineChartPropsSchema = z.object({
  subtype: z.enum(["line", "smooth"]).optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const areaChartPropsSchema = z.object({
  subtype: z.enum(["area", "area-stacked"]).optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const pieChartPropsSchema = z.object({
  subtype: z.enum(["pie", "donut"]).optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const scatterChartPropsSchema = z.object({
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const bubbleChartPropsSchema = z.object({
  minRadius: z.number().optional(),
  maxRadius: z.number().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const timeseriesPropsSchema = z.object({
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const heatmapChartPropsSchema = z.object({
  minColor: z.string().optional(),
  maxColor: z.string().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const treemapChartPropsSchema = z.object({
  parentColumn: z.string().optional(),
  colorColumn: z.string().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const densityHeatmapPropsSchema = z.object({
  xColumn: z.string().optional(),
  yColumn: z.string().optional(),
  valueColumn: z.string().optional(),
  gradient: z.array(z.object({
      offset: z.number(),
      color: z.string(),
    })).optional(),
  radius: z.number().optional(),
  aggregation: z.enum(["max", "sum", "mean", "count"]).optional(),
  showTooltip: z.boolean().optional(),
  showLegend: z.boolean().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
});

export const metricGridPropsSchema = z.object({
  direction: z.enum(["grid", "row"]).optional(),
});

export const dataTablePropsSchema = z.object({
  pageSize: z.number().optional(),
  pageSizeOptions: z.array(z.number()).optional(),
  sortable: z.boolean().optional(),
  resizable: z.boolean().optional(),
  rowStyle: z.array(z.object({
      condition: z.string(),
      className: z.string().optional(),
      style: z.record(z.string()).optional(),
    })).optional(),
  rowAccent: z.object({
    column: z.string(),
    colorMap: z.record(z.string()),
    default: z.string().optional(),
    columns: z.union([z.array(z.string()), z.string()]).optional(),
  }).optional(),
  rowDetail: z.object({
    mode: z.enum(["single", "multi"]).optional(),
    columns: z.array(z.object({
        id: z.string(),
        label: z.string().optional(),
      })).optional(),
  }).optional(),
  rowHeight: z.union([z.number(), z.string()]).optional(),
  expandable: z.object({
    idColumn: z.string(),
    parentColumn: z.string(),
    defaultExpanded: z.union([z.number(), z.boolean(), z.boolean()]).optional(),
  }).optional(),
  selection: z.enum(["single", "multi", "none"]).optional(),
  selectionKey: z.string().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
});

export const gridTablePropsSchema = z.object({
  columnHeaders: z.boolean().optional(),
  rowHeaders: z.boolean().optional(),
  cellDisplay: z.record(z.enum(["number", "boolean", "text", "color", "badge"])).optional(),
  compact: z.boolean().optional(),
  stripe: z.enum(["rows", "columns", "both"]).optional(),
  verticalLines: z.boolean().optional(),
  transpose: z.boolean().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
});

export const metricPropsSchema = z.object({
  text: z.string().optional(),
  value: z.string().optional(),
  subtype: z.enum(["card", "card2", "plain-text", "quota"]).optional(),
  pattern: z.string().optional(),
  html: z.object({
    template: z.string().optional(),
    javascript: z.string().optional(),
  }).optional(),
  sparklineData: z.array(z.number()).optional(),
  trend: z.enum(["up", "down", "flat"]).optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
});

export const meterPropsSchema = z.object({
  end: z.number().optional(),
  warning: z.number().optional(),
  critical: z.number().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const selectorPropsSchema = z.object({
  subtype: z.enum(["dropdown", "slider", "labels"]).optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
});

export const mapPropsSchema = z.object({
  subtype: z.enum(["regions", "markers"]).optional(),
  colorScheme: z.string().optional(),
  mapName: z.string().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const badgePropsSchema = z.object({
  column: z.string().optional(),
  colorMap: z.record(z.string()).optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
});

export const countdownPropsSchema = z.object({
  deadlineColumn: z.string().optional(),
  format: z.enum(["full", "compact", "days-only"]).optional(),
  warningThreshold: z.string().optional(),
  criticalThreshold: z.string().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
});

export const timelinePropsSchema = z.object({
  startColumn: z.string().optional(),
  endColumn: z.string().optional(),
  labelColumn: z.string().optional(),
  categoryColumn: z.string().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const graphPropsSchema = z.object({
  layout: z.enum(["none", "force", "circular"]).optional(),
  sourceColumn: z.string().optional(),
  targetColumn: z.string().optional(),
  valueColumn: z.string().optional(),
  directed: z.boolean().optional(),
  nodeLabelColumn: z.string().optional(),
  nodeColorColumn: z.string().optional(),
  nodeColorMap: z.record(z.string()).optional(),
  nodeSizeColumn: z.string().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
  resizable: z.boolean().optional(),
  zoom: z.boolean().optional(),
  maxWidth: z.number().optional(),
  maxHeight: z.number().optional(),
  legend: z.object({
    show: z.boolean().optional(),
    position: z.enum(["left", "right", "bottom", "top"]).optional(),
  }).optional(),
  margin: z.object({
    top: z.number().optional(),
    right: z.number().optional(),
    bottom: z.number().optional(),
    left: z.number().optional(),
  }).optional(),
  xAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  yAxis: z.object({
    title: z.string().optional(),
    showLabels: z.boolean().optional(),
    labelAngle: z.number().optional(),
  }).optional(),
  grid: z.object({
    x: z.boolean().optional(),
    y: z.boolean().optional(),
  }).optional(),
  extra: z.record(z.unknown()).optional(),
});

export const eventTimelinePropsSchema = z.object({
  layout: z.enum(["horizontal", "vertical", "compact"]).optional(),
  pageSize: z.number().optional(),
  strategyKey: z.string().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
});

export const groupedViewPropsSchema = z.object({
  groupBy: z.union([z.object({
      sourceId: z.string(),
      columnId: z.string(),
      strategy: z.union([z.object({
          mode: z.string(),
        }), z.object({
          mode: z.string(),
          unit: z.enum(["QUARTER", "MONTH", "DAY_OF_WEEK", "HOUR", "MINUTE", "SECOND"]),
        }), z.object({
          mode: z.string(),
          preferredUnit: z.enum(["QUARTER", "MONTH", "DAY_OF_WEEK", "HOUR", "MINUTE", "SECOND", "MILLISECOND", "HUNDRETH", "TENTH", "DAY", "WEEK", "YEAR", "DECADE", "CENTURY", "MILLENIUM"]).optional(),
        }), z.object({
          mode: z.string(),
          preferredUnit: z.enum(["QUARTER", "MONTH", "DAY_OF_WEEK", "HOUR", "MINUTE", "SECOND", "MILLISECOND", "HUNDRETH", "TENTH", "DAY", "WEEK", "YEAR", "DECADE", "CENTURY", "MILLENIUM"]).optional(),
        })]),
      maxIntervals: z.number(),
      emptyIntervals: z.boolean(),
      ascendingOrder: z.boolean(),
      firstMonthOfYear: z.union([z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number()]).optional(),
      firstDayOfWeek: z.union([z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number()]).optional(),
    }), z.array(z.object({
        sourceId: z.string(),
        columnId: z.string(),
        strategy: z.union([z.object({
            mode: z.string(),
          }), z.object({
            mode: z.string(),
            unit: z.enum(["QUARTER", "MONTH", "DAY_OF_WEEK", "HOUR", "MINUTE", "SECOND"]),
          }), z.object({
            mode: z.string(),
            preferredUnit: z.enum(["QUARTER", "MONTH", "DAY_OF_WEEK", "HOUR", "MINUTE", "SECOND", "MILLISECOND", "HUNDRETH", "TENTH", "DAY", "WEEK", "YEAR", "DECADE", "CENTURY", "MILLENIUM"]).optional(),
          }), z.object({
            mode: z.string(),
            preferredUnit: z.enum(["QUARTER", "MONTH", "DAY_OF_WEEK", "HOUR", "MINUTE", "SECOND", "MILLISECOND", "HUNDRETH", "TENTH", "DAY", "WEEK", "YEAR", "DECADE", "CENTURY", "MILLENIUM"]).optional(),
          })]),
        maxIntervals: z.number(),
        emptyIntervals: z.boolean(),
        ascendingOrder: z.boolean(),
        firstMonthOfYear: z.union([z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number()]).optional(),
        firstDayOfWeek: z.union([z.number(), z.number(), z.number(), z.number(), z.number(), z.number(), z.number()]).optional(),
      }))]),
  preset: z.enum(["spreadsheet", "sectioned", "list"]).optional(),
  groupDisplay: z.enum(["table-row", "section-heading"]).optional(),
  contentDisplay: z.enum(["list", "table"]).optional(),
  defaultExpanded: z.boolean().optional(),
  showGroupSummary: z.boolean().optional(),
  aggregations: z.array(z.object({
      column: z.string(),
      fn: z.union([z.object({
          fn: z.string(),
        }), z.object({
          fn: z.string(),
        }), z.object({
          fn: z.string(),
        }), z.object({
          fn: z.string(),
        }), z.object({
          fn: z.string(),
        }), z.object({
          fn: z.string(),
        }), z.object({
          fn: z.string(),
        }), z.object({
          fn: z.string(),
          separator: z.string(),
        }), z.object({
          fn: z.string(),
          separator: z.string(),
        })]),
    })).optional(),
  order: z.enum(["asc", "desc"]).optional(),
  emptyGroups: z.boolean().optional(),
  columnConfig: z.array(z.object({
      id: z.string(),
      label: z.string().optional(),
      sortable: z.boolean().optional(),
      visible: z.boolean().optional(),
      width: z.string().optional(),
      minWidth: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      filterable: z.boolean().optional(),
    })).optional(),
  rowStyle: z.array(z.object({
      condition: z.string(),
      className: z.string().optional(),
      style: z.record(z.string()).optional(),
    })).optional(),
  rowAccent: z.object({
    column: z.string(),
    colorMap: z.record(z.string()),
    default: z.string().optional(),
    columns: z.union([z.array(z.string()), z.string()]).optional(),
  }).optional(),
  selection: z.enum(["single", "multi", "none"]).optional(),
  sortable: z.boolean().optional(),
  clientSort: z.boolean().optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  csvExport: z.boolean().optional(),
  lookup: lookupSchema,
  rowCount: z.number().optional(),
  rowOffset: z.number().optional(),
  columns: z.array(z.object({
      id: z.string(),
      name: z.string().optional(),
      expression: z.string().optional(),
      pattern: z.string().optional(),
      empty: z.string().optional(),
      width: z.string().optional(),
      align: z.enum(["start", "center", "end"]).optional(),
      sortable: z.boolean().optional(),
      minWidth: z.string().optional(),
      pill: z.record(z.string()).optional(),
    })).optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
});

export const iframePluginPropsSchema = z.object({
  componentId: z.string(),
  settings: z.record(z.unknown()).optional(),
  lookup: lookupSchema.optional(),
  title: z.string().optional(),
  visible: z.boolean().optional(),
  width: z.string().optional(),
  height: z.string().optional(),
  filter: z.object({
    enabled: z.boolean().optional(),
    notification: z.boolean().optional(),
    listening: z.boolean().optional(),
    selfApply: z.boolean().optional(),
    group: z.string().optional(),
    drillDown: z.object({
      target: z.string(),
      parameters: z.record(z.string()).optional(),
    }).optional(),
  }).optional(),
  refresh: z.object({
    interval: z.number().optional(),
    showStaleIndicator: z.boolean().optional(),
  }).optional(),
});

export const textInputPropsSchema = z.object({
  placeholder: z.string().optional(),
  maxLength: z.number().optional(),
  field: z.string(),
  label: z.string().optional(),
  required: z.boolean().optional(),
  readonly: z.boolean().optional(),
  submit: z.object({
    url: z.string(),
    method: z.enum(["POST", "PUT"]).optional(),
    fieldName: z.string().optional(),
    clearOnSubmit: z.boolean().optional(),
    onSuccess: z.object({
      refresh: z.array(z.string()).optional(),
      message: z.string().optional(),
    }).optional(),
    onError: z.object({
      message: z.string().optional(),
    }).optional(),
  }).optional(),
});

export const numberInputPropsSchema = z.object({
  min: z.number().optional(),
  max: z.number().optional(),
  step: z.number().optional(),
  field: z.string(),
  label: z.string().optional(),
  required: z.boolean().optional(),
  readonly: z.boolean().optional(),
  submit: z.object({
    url: z.string(),
    method: z.enum(["POST", "PUT"]).optional(),
    fieldName: z.string().optional(),
    clearOnSubmit: z.boolean().optional(),
    onSuccess: z.object({
      refresh: z.array(z.string()).optional(),
      message: z.string().optional(),
    }).optional(),
    onError: z.object({
      message: z.string().optional(),
    }).optional(),
  }).optional(),
});

export const dropdownPropsSchema = z.object({
  options: z.union([z.object({
      values: z.array(z.string()),
    }), z.object({
      dataset: z.string(),
      labelColumn: z.string(),
      valueColumn: z.string(),
      filterField: z.string().optional(),
      filterColumn: z.string().optional(),
    })]),
  field: z.string(),
  label: z.string().optional(),
  required: z.boolean().optional(),
  readonly: z.boolean().optional(),
  submit: z.object({
    url: z.string(),
    method: z.enum(["POST", "PUT"]).optional(),
    fieldName: z.string().optional(),
    clearOnSubmit: z.boolean().optional(),
    onSuccess: z.object({
      refresh: z.array(z.string()).optional(),
      message: z.string().optional(),
    }).optional(),
    onError: z.object({
      message: z.string().optional(),
    }).optional(),
  }).optional(),
});

export const checkboxPropsSchema = z.object({
  field: z.string(),
  label: z.string().optional(),
  required: z.boolean().optional(),
  readonly: z.boolean().optional(),
  submit: z.object({
    url: z.string(),
    method: z.enum(["POST", "PUT"]).optional(),
    fieldName: z.string().optional(),
    clearOnSubmit: z.boolean().optional(),
    onSuccess: z.object({
      refresh: z.array(z.string()).optional(),
      message: z.string().optional(),
    }).optional(),
    onError: z.object({
      message: z.string().optional(),
    }).optional(),
  }).optional(),
});

export const datePickerPropsSchema = z.object({
  min: z.string().optional(),
  max: z.string().optional(),
  field: z.string(),
  label: z.string().optional(),
  required: z.boolean().optional(),
  readonly: z.boolean().optional(),
  submit: z.object({
    url: z.string(),
    method: z.enum(["POST", "PUT"]).optional(),
    fieldName: z.string().optional(),
    clearOnSubmit: z.boolean().optional(),
    onSuccess: z.object({
      refresh: z.array(z.string()).optional(),
      message: z.string().optional(),
    }).optional(),
    onError: z.object({
      message: z.string().optional(),
    }).optional(),
  }).optional(),
});

export const textareaPropsSchema = z.object({
  rows: z.number().optional(),
  maxLength: z.number().optional(),
  field: z.string(),
  label: z.string().optional(),
  required: z.boolean().optional(),
  readonly: z.boolean().optional(),
  submit: z.object({
    url: z.string(),
    method: z.enum(["POST", "PUT"]).optional(),
    fieldName: z.string().optional(),
    clearOnSubmit: z.boolean().optional(),
    onSuccess: z.object({
      refresh: z.array(z.string()).optional(),
      message: z.string().optional(),
    }).optional(),
    onError: z.object({
      message: z.string().optional(),
    }).optional(),
  }).optional(),
});

export const schemaFormPropsSchema = z.object({
  schema: fieldSchemaZod.optional(),
  mode: z.enum(["display", "edit"]).optional(),
  forceCreate: z.boolean().optional(),
  validateOnBlur: z.boolean().optional(),
  excludeFields: z.array(z.string()).optional(),
  fieldOrder: z.array(z.string()).optional(),
  fields: z.array(z.string()).optional(),
  labels: z.record(z.string()).optional(),
  fieldsOnly: z.boolean().optional(),
});

export const actionButtonPropsSchema = z.object({
  label: z.string(),
  url: z.string(),
  method: z.enum(["POST", "PUT", "DELETE"]).optional(),
  body: z.record(z.unknown()).optional(),
  headers: z.record(z.string()).optional(),
  confirm: z.string().optional(),
  style: z.enum(["primary", "danger", "secondary", "ghost", "outline"]).optional(),
  disabled: z.boolean().optional(),
  disabledWhen: z.string().optional(),
  onSuccess: z.object({
    refresh: z.array(z.string()).optional(),
    message: z.string().optional(),
  }).optional(),
  onError: z.object({
    message: z.string().optional(),
  }).optional(),
});

export const formScopePropsSchema = z.object({
  schema: fieldSchemaZod.optional(),
  validateOnBlur: z.boolean().optional(),
  mode: z.enum(["display", "edit"]).optional(),
  forceCreate: z.boolean().optional(),
});

export const submitButtonPropsSchema = z.object({
  label: z.string(),
  style: z.enum(["primary", "danger", "secondary", "ghost", "outline"]).optional(),
  disabled: z.boolean().optional(),
});

export const componentSchemaMap: ReadonlyMap<string, z.ZodType> = new Map([
  ["grid", gridPropsSchema],
  ["columns", columnsPropsSchema],
  ["rows", rowsPropsSchema],
  ["stack", stackPropsSchema],
  ["tabs", tabsPropsSchema],
  ["pills", pillsPropsSchema],
  ["sidebar", sidebarPropsSchema],
  ["tree", treePropsSchema],
  ["menu", menuPropsSchema],
  ["accordion", accordionPropsSchema],
  ["carousel", carouselPropsSchema],
  ["split", splitPropsSchema],
  ["dock-bar", dockBarPropsSchema],
  ["host-panel", hostPanelPropsSchema],
  ["floating-workspace", floatingWorkspacePropsSchema],
  ["panel", panelPropsSchema],
  ["html", htmlPropsSchema],
  ["markdown", markdownPropsSchema],
  ["title", titlePropsSchema],
  ["lazy-page", lazyPagePropsSchema],
  ["page", pagePropsSchema],
  ["bar-chart", barChartPropsSchema],
  ["line-chart", lineChartPropsSchema],
  ["area-chart", areaChartPropsSchema],
  ["pie-chart", pieChartPropsSchema],
  ["scatter-chart", scatterChartPropsSchema],
  ["bubble-chart", bubbleChartPropsSchema],
  ["timeseries", timeseriesPropsSchema],
  ["heatmap-chart", heatmapChartPropsSchema],
  ["treemap-chart", treemapChartPropsSchema],
  ["density-heatmap", densityHeatmapPropsSchema],
  ["metric-grid", metricGridPropsSchema],
  ["data-table", dataTablePropsSchema],
  ["grid-table", gridTablePropsSchema],
  ["metric", metricPropsSchema],
  ["meter", meterPropsSchema],
  ["selector", selectorPropsSchema],
  ["map", mapPropsSchema],
  ["badge", badgePropsSchema],
  ["countdown", countdownPropsSchema],
  ["timeline", timelinePropsSchema],
  ["graph", graphPropsSchema],
  ["event-timeline", eventTimelinePropsSchema],
  ["grouped-view", groupedViewPropsSchema],
  ["iframe-plugin", iframePluginPropsSchema],
  ["input", textInputPropsSchema],
  ["number-input", numberInputPropsSchema],
  ["select", dropdownPropsSchema],
  ["checkbox", checkboxPropsSchema],
  ["date-picker", datePickerPropsSchema],
  ["textarea", textareaPropsSchema],
  ["schema-form", schemaFormPropsSchema],
  ["action-button", actionButtonPropsSchema],
  ["form-scope", formScopePropsSchema],
  ["submit-button", submitButtonPropsSchema],
]);
